
services:
  api:
    container_name: shopper-api
    image: node:lts
    ports:
      - 3333:3333
    command: sh -c "npm run dev"
    working_dir: /app
    volumes:
      - .:/app
    env_file: .env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}